config/routes.rb
Gadgets::Application.routes.draw do
  resources :gadgets do
    resources :images
  end

  resource :images

  devise_for :users

  root 'home#index'

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
  has_many :images

  def self.search(search, user_id)
    if search
      where('name LIKE ? and user_id = ?', "%#{search}%", user_id)
    else
      where('user_id = ?', user_id)
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  mount_uploader :file, ImageUploader
  belongs_to :gadget
 end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable

  has_many :gadgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    gadgets_path
  end

  protected

  def check_current_user
    unless current_user
      redirect_to root_path, notice: 'Please log in.'
      return
    end
  end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

  before_action :check_current_user

  def index
    @gadgets = Gadget.search(params[:search], current_user.id)
  end

  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = Gadget.new(gadget_params)
    @gadget.user = current_user

    if @gadget.save
      redirect_to gadgets_path, notice: 'Gadget was successfully created.'
    else
      render action: 'new'
    end
  end

  private


  def gadget_params
    params.require(:gadget).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :check_current_user

  def new
    @image = Image.new
    unless params[:gadget_id]
      redirect_to root_path, error: "No gadget id specified."
      return
    end
    @gadget = Gadget.find(params[:gadget_id])
  end

  def create
    @image = Image.new(file: params[:image][:file], gadget_id: params[:image][:gadget_id])
    @image.save!
    redirect_to gadgets_path, notice: "Image has been added."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
  def covers(gadgets)
    covers = []
    gadgets.each do |gadget|
      image =  gadget.images.first ? gadget.images.first.file.large.url : ''
      covers << {"title" => gadget.name, "description" => gadget.description, "image" =>  image }
    end
    covers.to_json.html_safe
  end
end

app/views/gadgets/_coverflow.html.erb
<div id="player"></div>
<script>
  coverflow('player').setup({
    flash: 'coverflow.swf',
    playlist: <%= covers(@gadgets) %>,
    width: 800,
    height: 300,
    backgroundcolor: '#ffffff',
    textstyle: 'color: black'
  });
</script>

app/views/gadgets/_large.html.erb
<% @gadgets.each do |gadget| %>
  <h3><%=gadget.name %></h3>
  <p><%= gadget.description %><p>
  <div class="panel">
    <% gadget.images.each do |image| %>
      <%= image_tag image.file.large %>
    <% end %>
  </div>
  <%= link_to "add image", new_gadget_image_path(gadget) %>
<% end %>

app/views/gadgets/_small.html.erb
<% @gadgets.each do |gadget| %>
  <h3><%=gadget.name %></h3>
  <p><%= gadget.description %><p>
  <div class="panel">
    <% gadget.images.each do |image| %>
      <%= image_tag image.file.thumbnail %>
    <% end %>
  </div>
  <%= link_to "add image", new_gadget_image_path(gadget) %>
<% end %>

app/views/gadgets/index.html.erb
<div class="btn-group">
  <%= link_to "List (Small)", gadgets_path(view_mode: 'small'), class: "btn btn-default" %>
  <%= link_to "List (Large)", gadgets_path(view_mode: 'large'), class: "btn btn-default" %>
  <%= link_to "Coverflow", gadgets_path(view_mode: 'coverflow'), class: "btn btn-default" %>
</div>
<h2>Your gadget collection</h2>
<% if current_user %>
  <%= link_to 'Add a new Gadget', new_gadget_path %>
<% end %>
<%= render(params[:view_mode] || 'small') %>

app/views/gadgets/new.html.erb
<h1>Add a new gadget</h1>

<%= form_for(@gadget) do |f| %>
  <% if @gadget.errors.any? %>
    <ul>
      <% @gadget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Gadgets</h1>
  <% if current_user %>
    <p><%= link_to "Manage your gadgets", gadgets_path, class: "btn btn-primary btn-lg" %></p>
  <% else %>
    <p>Please log in to manage your gadgets.</p>
  <% end %>
</div>

app/views/images/new.html.erb
<div class="container">
  <h2>Images</h2>
  <p> Add an image for gadget <%= @gadget.name %></p>
  <%= form_for @image, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <%= f.hidden_field :gadget_id, value: @gadget.id %>
    <span class="btn btn-success fileinput-button">
      <i class="icon-plus icon-white"></i>
      <%= f.file_field :file %>
    </span>
    <button type="submit" class="btn btn-primary start">
      <i class="icon-upload icon-white"></i>
      <span>Start upload</span>
    </button>
  <% end %>

</div>

<script type="text/javascript" charset="utf-8">
var fileUploadErrors = {
maxFileSize: 'File is too big',
             minFileSize: 'File is too small',
             acceptFileTypes: 'Filetype not allowed',
             maxNumberOfFiles: 'Max number of files exceeded',
             uploadedBytes: 'Uploaded bytes exceed file size',
             emptyResult: 'Empty file upload result'
};

$(function () {
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload();
    //
    // Load existing files:
    $.getJSON($('#fileupload').prop('action'), function (files) {
      var fu = $('#fileupload').data('blueimpFileupload'),
      template;
      fu._adjustMaxNumberOfFiles(-files.length);
      console.log(files);
      template = fu._renderDownload(files)
      .appendTo($('#fileupload .files'));
      // Force reflow:
      fu._reflow = fu._transition && template.length &&
      template[0].offsetWidth;
      template.addClass('in');
      $('#loading').remove();
      });

    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gadgets</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to "Gadgets", "/", class: 'navbar-brand' %>
        </div>

        <% if current_user %>
          <%= form_tag gadgets_path, method: 'get', class: 'navbar-form navbar-left' do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], class: 'form-control' %>
            </div>
            <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
            </p>
          <% end %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% unless current_user %>
            <li><%= link_to "sign up", new_user_registration_path %> </li>
          <% end %>
          <li>
          <% if current_user %>
            <li><%= link_to "logout", destroy_user_session_path, method: 'delete'  %> </li>
          <% else %>
            <li><%= link_to "login", new_user_session_path  %> </li>
          <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% [:notice, :error, :alert].each do |level| %>
    <% unless flash[level].blank? %>
      <div class="alert alert-<%= flash_class(level) %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= flash[level] %>
      </div>
    <% end %>
  <% end %>
  <%= yield %>
</body>
</html>